### ISSUE TITLE
the software told me to add a screenshot

### ISSUE THREAD

**Issue by Kraaven** [SirDank/dank.tool#2]
<img width="670" alt="dank error" src="https://user-images.githubusercontent.com/106032882/200128323-fd3299c9-361b-4368-ab31-d6689475f971.png">

**Comment by SirDank** [comment]
could you specify which module was used?

**Comment by Kraaven** [comment]
Module 1, server builder

**Comment by SirDank** [comment]
Thank you for reporting this, an update will be pushed shortly, in the meanwhile please be patient, thank you!

**Comment by SirDank** [comment]
fixed!
https://github.com/SirDank/dank.tool/commit/3ab7b8d95d73729f29d1d37b716b0714dcfe7522
