### ISSUE TITLE
Text alignment bug

### ISSUE THREAD

**Issue by bachig26** [SirDank/dank.tool#6]
As you can see in the screenshots, the alignment is proper and isn't relative to the window size.

I can't get the desired result as provided in the [preview](https://user-images.githubusercontent.com/52797753/246598313-64b4fa5c-ada6-4970-9970-4c032fe03755.png).

I hoping for some solution or bug fix in future release.

#### Screenshot

**1. Fullscreen**

![dank tool_fullscreen](https://github.com/SirDank/dank.tool/assets/96393348/2dec3927-ed5e-47cf-be3c-8bfbd07bac4c)

**2. Splitscreen**

![dank tool_splitscreen](https://github.com/SirDank/dank.tool/assets/96393348/97e4b7ad-351c-47c8-9b9e-037592fceb33)

#### Windows Info

Edition: Win 10 Home Single Language
Version: 22H2
Display Resolution: 1920 x 1080

**Comment by SirDank** [comment]
@bachig26 if im understanding this correctly, this only happens when you change the window size correct?

**Comment by bachig26** [comment]
> @bachig26 if im understanding this correctly, this only happens when you change the window size correct?

Yes, and even in full display size.

**Comment by SirDank** [comment]
whoops, didn't mean to close this issue, you can now enter "refresh" to re-align everything!
