### ISSUE TITLE
Possible 3rd party module support

### ISSUE THREAD

**Issue by bachig26** [SirDank/dank.tool#7]
In case, one needs a personally hand-picked executables for their needs and which may not be available in official modules list.

This way the users can make their own module and make a link to it within the dank.tool to the modules directory.

I think this might have a good use of customization in terms of tools to installed and possibly more.

**Comment by SirDank** [comment]
this is a very good idea, I will look forward to implementing it!

What will be available in a upcoming update:
- Users would be able to create their own `project.py` script and place it under the `__local_modules__` folder and execute it from the main menu.

What is already possible:
- If a user wishes to have their projects available to every dank.tool user they must first fork this repo, add their `project.py` to `__modules__` folder and then finally create a pull request. I will validate the submitted Python script on several criteria and if it passes, I will perform compatibility and performance edits to the code and finally publish it.
- Ideally ( when possible ) the user must first test out their project by executing it via the dank.tool before they submit a pull request.
